[project]  # https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
name = "snapszer"
version = "0.1.0"
dependencies = []
requires-python = ">=3.14"
authors = [{name="alkenderesi"}]
description = "Snapszer card game"
readme = "README.md"
license = "Unlicense"
license-files = ["LICENSE"]
keywords = ["snapszer", "schnapsen", "card game"]
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: The Unlicense (Unlicense)",
  "Natural Language :: English",
  "Natural Language :: Hungarian",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
  "Topic :: Games/Entertainment :: Board Games",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]  # https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls
Repository = "https://github.com/alkenderesi/snapszer"
Wikipedia = "https://en.wikipedia.org/wiki/Schnapsen"

[build-system]  # https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#declaring-the-build-backend
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]  # https://docs.astral.sh/uv/concepts/build-backend/#modules
module-name = "snapszer"
module-root = ""

[dependency-groups]  # https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-groups
test = [
  "pre-commit>=4.6.2,<5",
]
